### ISSUE TITLE
Is this bundle useful for you? Leave feedback here

### ISSUE THREAD

**Issue by regularjack** [regularjack/frontend-bundle#13]
https://github.com/symfony/symfony-standard/pull/860#issuecomment-146062230

**Comment by sroze** [comment]
Looks interesting. Do you have any demo app somewhere?

**Comment by regularjack** [comment]
@sroze I'm using it in a non-open-source project but, since I can't show that, I created a very simple example app: https://github.com/regularjack/frontend-bundle-example-app

Here's the steps it took to set it up:
```
symfony new frontend-bundle-example-app
cd frontend-bundle-example-app

composer require regularjack/frontend-bundle
npm install -g bower
npm install -g gulp

app/console rj_frontend:setup --no-interaction
```

Here's the [diff](https://github.com/regularjack/frontend-bundle-example-app/commit/6e2d738aa28c67e4855ac5fb8f902110167396d3) with the out-of-the-box Symfony app.

You can run it with:
```
app/console server:start
gulp
```
