### ISSUE TITLE
Get asset URL from the PHP code?

### ISSUE THREAD

**Issue by alister** [regularjack/frontend-bundle#25]
Is there a service or some other way that would allow the PHP code (as distinct from the twig templates, via the `asset()` function), to easily get the URL of an asset, via the appropriate versioning strategy?

**Comment by regularjack** [comment]
You can use the `assets.packages` service, which is what the Twig `asset()` function calls under the hood:

```php
/* @var Symfony\Component\Asset\Packages */
$packages = $container->get('assets.packages');

$url = $packages->getUrl('images/foo.png');
```

If you're using a Symfony version earlier than 2.7, use the `'templating.helper.assets` service instead:

```php
$assets = $container->get('templating.helper.assets);

$url = $assets->getUrl('images/foo.png');
```

Note that this isn't specific to this bundle, it works in a standard Symfony project too.
