### ISSUE TITLE
Deprecated npm package

### ISSUE THREAD

**Issue by psyray** [regularjack/frontend-bundle#30]
Hi,

While I launch the setup those warnings appears
```
npm WARN deprecated
 gulp-minify-css@1.2.4: Please use gulp-clean-css

npm WARN
 deprecated
 minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN prefer global node-gyp@3.6.2 should be installed with -g
```
Maybe you should update version or change package ?
Do you think It's important ?

**Comment by regularjack** [comment]
Thanks for reporting this. I just released [v0.2.0](https://github.com/regularjack/frontend-bundle/releases/tag/v0.2.0) which fixes these issues.

Please make sure you're using the (global) `gulp-cli` instead of `gulp`:

```shell
gulp uninstall -g gulp
gulp install -g gulp-cli
```

**Comment by psyray** [comment]
Thanks
Maybe you should modify the [next steps](http://frontend-bundle.readthedocs.io/en/stable/setup.html#next-steps) parts to use gulp-cli instead of gulp ?

**Comment by psyray** [comment]
To uninstall gulp and install gulp-cli I think you would say
```
npm uninstall -g gulp
npm install -g gulp-cli
```
:)

**Comment by psyray** [comment]
Thanks :+1:
